pdflatex

diff --git a/trunk/devel/TeX/chklref/configure b/trunk/devel/TeX/chklref/configure
--- a/trunk/devel/TeX/chklref/configure
+++ b/trunk/devel/TeX/chklref/configure
@@ -624,6 +624,7 @@ binfiles
 sharefiles
 texfiles
 latex_path
+pdflatex_path
 perl_path
 gs_path
 dvips_path
@@ -1812,7 +1813,51 @@ if test "x$latex_path" = "x" ; then
 echo "$as_me: error: \"latex not found\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
+# Extract the first word of "pdflatex", so it can be a program name with args.
+set dummy pdflatex; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_pdflatex_path+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $pdflatex_path in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_pdflatex_path="$pdflatex_path" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_pdflatex_path="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
 
+  ;;
+esac
+fi
+pdflatex_path=$ac_cv_path_pdflatex_path
+if test -n "$pdflatex_path"; then
+  { echo "$as_me:$LINENO: result: $pdflatex_path" >&5
+echo "${ECHO_T}$pdflatex_path" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+if test "x$pdflatex_path" = "x" ; then
+   { { echo "$as_me:$LINENO: error: \"pdflatex not found\"" >&5
+echo "$as_me: error: \"pdflatex not found\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -1858,8 +1903,6 @@ if test "x$perl_path" = "x" ; then
 echo "$as_me: error: \"perl not found\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
-
-
 # Extract the first word of "gs", so it can be a program name with args.
 set dummy gs; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -1905,7 +1948,6 @@ if test "x$gs_path" = "x" ; then
 echo "$as_me: error: \"ghostscript interpreter not found\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
-
 # Extract the first word of "dvips", so it can be a program name with args.
 set dummy dvips; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -1951,6 +1993,13 @@ if test "x$gs_path" = "x" ; then
 echo "$as_me: error: \"dvips not found\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
+
+
+
+
+
+
+
 
 texmf_cnf=$(kpsewhich texmf.cnf);
 TEXMFLOCAL=$(grep -e 'TEXMFLOCAL *= *' $texmf_cnf | sed 's/TEXMFLOCAL *= *//' | tail -n 1)
@@ -2636,6 +2685,7 @@ binfiles!$binfiles$ac_delim
 sharefiles!$sharefiles$ac_delim
 texfiles!$texfiles$ac_delim
 latex_path!$latex_path$ac_delim
+pdflatex_path!$pdflatex_path$ac_delim
 perl_path!$perl_path$ac_delim
 gs_path!$gs_path$ac_delim
 dvips_path!$dvips_path$ac_delim
@@ -2644,7 +2694,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 52; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 53; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
